import { formatDayLabel, formatDistanceKm, formatDuration, formatTimeRange } from '../trips/format';
import { Trip } from '../trips/types';
import { PAGE_HEIGHT, PAGE_WIDTH, PdfDocument } from './pdf';
import { DIRECTION_LABELS, ReportSummary } from './summary';

const BLUE: [number, number, number] = [0, 0.48, 1];
const WHITE: [number, number, number] = [1, 1, 1];
const MUTED: [number, number, number] = [0.42, 0.45, 0.5];
const LIGHT: [number, number, number] = [0.96, 0.97, 0.98];
const RULE: [number, number, number] = [0.9, 0.9, 0.92];

const MARGIN = 40;
const ROW = 20;
const COLUMNS = [
  { title: 'Date', x: MARGIN + 8 },
  { title: 'Time', x: MARGIN + 130 },
  { title: 'Duration', x: MARGIN + 250 },
  { title: 'Distance', x: MARGIN + 330 },
  { title: 'Direction', x: MARGIN + 420 },
];

export interface ReportInput {
  periodLabel: string;
  generatedAt: number;
  summary: ReportSummary;
  trips: Trip[];
}

export function buildReportPdf({ periodLabel, generatedAt, summary, trips }: ReportInput): Uint8Array {
  const pdf = new PdfDocument();
  const width = PAGE_WIDTH - MARGIN * 2;

  // Header band
  pdf.rect(0, 0, PAGE_WIDTH, 96, BLUE);
  pdf.text(MARGIN, 48, 'Commute Report', { bold: true, size: 22, color: WHITE });
  pdf.text(MARGIN, 72, periodLabel, { size: 12, color: WHITE });

  // Summary tiles
  let y = 124;
  const tiles = [
    { label: 'Trips', value: String(summary.tripCount) },
    { label: 'Total time', value: formatDuration(summary.totalSeconds) },
    { label: 'Distance', value: formatDistanceKm(summary.totalMeters) },
    { label: 'Avg per trip', value: formatDuration(summary.avgSecondsPerTrip) },
  ];
  const tileWidth = (width - 3 * 10) / 4;
  tiles.forEach((tile, i) => {
    const x = MARGIN + i * (tileWidth + 10);
    pdf.rect(x, y, tileWidth, 58, LIGHT);
    pdf.text(x + 10, y + 24, tile.value, { bold: true, size: 15 });
    pdf.text(x + 10, y + 44, tile.label, { size: 9, color: MUTED });
  });

  y += 84;
  const { work, home } = summary.byDirection;
  const avg = (t: { count: number; totalSeconds: number }) => formatDuration(t.count ? t.totalSeconds / t.count : 0);
  pdf.text(MARGIN, y, `To work: ${work.count} trips, avg ${avg(work)}`, { size: 10 });
  pdf.text(MARGIN + width / 2, y, `To home: ${home.count} trips, avg ${avg(home)}`, { size: 10 });
  y += 16;
  pdf.text(MARGIN, y, `Days with commutes: ${summary.daysWithTrips}`, { size: 10, color: MUTED });

  // Trips table
  y += 30;
  const tableHeader = () => {
    pdf.rect(MARGIN, y, width, ROW, LIGHT);
    COLUMNS.forEach((c) => pdf.text(c.x, y + 14, c.title, { bold: true, size: 9, color: MUTED }));
    y += ROW;
  };
  tableHeader();

  if (trips.length === 0) {
    pdf.text(MARGIN + 8, y + 18, 'No trips in this period.', { size: 10, color: MUTED });
  }

  for (const trip of trips) {
    if (y + ROW > PAGE_HEIGHT - 60) {
      pdf.addPage();
      y = MARGIN;
      tableHeader();
    }
    const cells = [
      formatDayLabel(trip.startedAt, true),
      formatTimeRange(trip.startedAt, trip.endedAt),
      formatDuration(trip.durationSeconds),
      formatDistanceKm(trip.distanceMeters),
      DIRECTION_LABELS[trip.direction] || '-',
    ];
    cells.forEach((cell, i) => pdf.text(COLUMNS[i].x, y + 14, cell, { size: 9.5 }));
    pdf.line(MARGIN, y + ROW, MARGIN + width, y + ROW, RULE);
    y += ROW;
  }

  // Footer on every page, once the page count is known
  const generated = formatDayLabel(generatedAt, true);
  for (let page = 0; page < pdf.pageCount; page++) {
    pdf.text(
      MARGIN,
      PAGE_HEIGHT - 28,
      `Generated by MYCE on ${generated}  -  Page ${page + 1} of ${pdf.pageCount}`,
      { size: 8, color: MUTED },
      page,
    );
  }

  return pdf.toBytes();
}
